### ISSUE TITLE
two instances of  " i'm "  without capitalization

### ISSUE THREAD

**Issue by npelmore** [COSC-310-Team1/ChatBot#17]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L55

https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L67

**Comment by benkeeley** [comment]
Fixed. 
Also changed i've to I've on line 68.
