### ISSUE TITLE
"Nueralink" misspelled, should be Neuralink

### ISSUE THREAD

**Issue by npelmore** [COSC-310-Team1/ChatBot#19]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L46

https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L48

https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L340

https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L341

**Comment by benkeeley** [comment]
fixed:  

"In 2016 I founded Neuralink, a company that focuses on bran-computer interactions.", 

"The main companies I have been involved in are: Zip2,SpaceX,Tesla,OpenAI,Neuralink and SolarCity"

//Neuralink
else if(sent.contains("neuralink")
