### ISSUE TITLE
That new line needs to be before you've

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#20]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L71

**Comment by benkeeley** [comment]
![Capture22](https://user-images.githubusercontent.com/77421122/109598031-48036b00-7acd-11eb-821e-ba12c0cee8ed.PNG)
fix: "I had a cameo in The Simpsons, The Big Bang theory, South Park, and Rick and Morty. Maybe\n\tyou've seen one of my episodes?"
