### ISSUE TITLE
new line needs to be before the favourite

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#21]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L55

**Comment by benkeeley** [comment]
![Capture21](https://user-images.githubusercontent.com/77421122/109597274-c6134200-7acc-11eb-8333-3fc983914c7d.PNG)

fix: "I really enjoyed Your Name, but i'm also a fan of Studio Ghibli. Princess Mononoke is one of my\n\tfavourite films by them."
