### ISSUE TITLE
Needs new line after to

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#22]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L56

**Comment by benkeeley** [comment]
![Capture20](https://user-images.githubusercontent.com/77421122/109597069-5b620680-7acc-11eb-8d69-06e37067f247.PNG)

fix: 	"My favourite airplane is the SR-71 Blackbird. The A-XII in X AE A-XII is the predecessor to\n\tthis plane."
