### ISSUE TITLE
New line after sold

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#23]
https://github.com/COSC-310-Team1/ChatBot/blob/73d2626a4404784d9d9ef3f13feec8b78d926cf2/ChatBotCosc310/src/Window.java#L44

**Comment by benkeeley** [comment]
![Capture10](https://user-images.githubusercontent.com/77421122/109596818-d0810c00-7acb-11eb-8ab9-4dcd4b405ed3.PNG)


Working fix: "I was the cofounder of X.com, which later merged with confinity to form paypal and was then \n\tsold to ebay for $1.5 Billion!" 

Will close when committed.
