### ISSUE TITLE
X.com response doesn't work

### ISSUE THREAD

**Issue by benkeeley** [COSC-310-Team1/ChatBot#24]
![Capture9](https://user-images.githubusercontent.com/77421122/109596099-6e73d700-7aca-11eb-8484-c173c20b3bc8.PNG)

I implemented replace '.' for the msg so that punctuation doesn't factor in responses. However this is a case in which it works opposite of intended. Consider changing X.com - > X&&com?

**Comment by veengren-s** [comment]
Since x.com was being split into "x" and "com", just changed it to look for "x" and "com" separately.
