### ISSUE TITLE
Need to change && between you and your to ||

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#3]
https://github.com/COSC-310-Team1/ChatBot/blob/b9b0ec71aaef0bdfcb5e409a24dd47c070fc3236/ChatBotCosc310/src/Window.java#L220

**Comment by benkeeley** [comment]
else if((sent.contains("old")||sent.contains("age"))&&(sent.contains("you")||sent.contains("your")))
