### ISSUE TITLE
Add new line and tab after the word fond with \n\t

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#4]
https://github.com/COSC-310-Team1/ChatBot/blob/b9b0ec71aaef0bdfcb5e409a24dd47c070fc3236/ChatBotCosc310/src/Window.java#L59

**Comment by benkeeley** [comment]
![Capture23](https://user-images.githubusercontent.com/77421122/109599230-b1847900-7acf-11eb-8d69-ee0124cc241d.PNG)
fixed: "My parents were Maye who was my mother and Errol who was my father. I am not very fond\n\tof my father."
