### ISSUE TITLE
Add recognition for school

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#5]
https://github.com/COSC-310-Team1/ChatBot/blob/b9b0ec71aaef0bdfcb5e409a24dd47c070fc3236/ChatBotCosc310/src/Window.java#L232

**Comment by benkeeley** [comment]
fix: else if(sent.contains("education")||sent.contains("school")

![Capture24](https://user-images.githubusercontent.com/77421122/109599505-2952a380-7ad0-11eb-9e08-d36aa0306d86.PNG)
