### ISSUE TITLE
This response doesn't function properly for &&'s and ||'s

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#7]
I sent when did you learn programming and when did you learn to program and neither worked

https://github.com/COSC-310-Team1/ChatBot/blob/b9b0ec71aaef0bdfcb5e409a24dd47c070fc3236/ChatBotCosc310/src/Window.java#L256

**Comment by benkeeley** [comment]
Sorry its meant to be asked,  how did you learn to program? or how did you learn to code? I knew we couldn't think of every possible response so figured I could leave it at that.  I'll add another line to fix the issue .
