### ISSUE TITLE
This response doesn't work

### ISSUE THREAD

**Issue by evanderpoel** [COSC-310-Team1/ChatBot#8]
https://github.com/COSC-310-Team1/ChatBot/blob/b9b0ec71aaef0bdfcb5e409a24dd47c070fc3236/ChatBotCosc310/src/Window.java#L265

**Comment by benkeeley** [comment]
![image](https://user-images.githubusercontent.com/77421122/109452787-5e45f400-7a05-11eb-8319-db51d3a090a7.png)

Sorry, I realize now that some of my responses are not as obvious as they should be , but I wanted the input to be:
what car do you drive?
what cars do you own?

I realize cars isn't in there so if fixed it to:
else if((sent.contains("cars")||sent.contains("car"))&&(sent.contains("drive")||sent.contains("own")))

There's no place for our intended responses yet so ill add a comment above it for now.
Will also leave this issue open, in case you guys think this response isn't flexible or worded weird and needs to be changed.
